package com.msc.gib.app.mufg;

public class Shared {
	public static enum BANKS {
		MUFG, MIZUHO, SMBC, NETBK
	};

	public static enum MUFG_ACTIONS {
		ZANDAKA_SHOUKAI, NYUSHUKKIN_MEISAI, FURIKOMI_NYUSHUKKIN_MEISAI, FURIKOMI_SHINSEI
	}

	public static enum PARAMETERS {
		ACTION, ACCOUNT_ID, INQUIRY_DATE_FROM, INQUIRY_DATE_TO, NEXT_KEYWORD, DEBIT_ACCOUNT_BRANCH_NO, DEBIT_ACCOUNT_TYPE_CODE, DEBIT_ACCOUNT_NO, APPLICANT_NAME, BENEFICIARY_CODE_1, PAYMENT_DATE, BENEFICIARY_CODE_2, BENEFICIARY_ACCOUNT_FINANCIAL_INSTITUTION_NO, BENEFICIARY_ACCOUNT_BRANCH_NO, BENEFICIARY_ACCOUNT_TYPE_CODE, BENEFICIARY_ACCOUNT_NAME_KANJI, BENEFICIARY_ACCOUNT_NO, BENEFICIARY_ACCOUNT_NAME_KANA, NOTES, ENTERED_AMOUNT, CHARGES_PAID_BY, PAYMENT_APPLICANT_NO, EDI_INFO
	}
}
